/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    models: Model;
    projects: Project;
    skills: Skill;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    models: ModelsSelect<false> | ModelsSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    skills: SkillsSelect<false> | SkillsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'nl') | ('en' | 'nl')[];
  globals: {
    'about-page': AboutPage;
    'contact-page': ContactPage;
    'skills-page': SkillsPage;
  };
  globalsSelect: {
    'about-page': AboutPageSelect<false> | AboutPageSelect<true>;
    'contact-page': ContactPageSelect<false> | ContactPageSelect<true>;
    'skills-page': SkillsPageSelect<false> | SkillsPageSelect<true>;
  };
  locale: 'en' | 'nl';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Upload .glb / .gltf files to use as the 3D object in a project.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "models".
 */
export interface Model {
  id: number;
  /**
   * Short internal name, e.g. "Vault safe"
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * The list of items shown on the homepage.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  /**
   * Small label shown above the title, e.g. "VISUAL STUDY · 2026"
   */
  category?: string | null;
  /**
   * Short description shown under the title.
   */
  description: string;
  /**
   * External links shown on this project's detail page, e.g. "Visit site", "GitHub", "App Store".
   */
  links?:
    | {
        /**
         * Button text, e.g. "Visit site"
         */
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Full case-study write-up, shown on this project's detail page. To color a heading (e.g. to mark which section of a model it belongs to), select its text and use "Text Color" in the toolbar.
   */
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Large image at the top of the project detail page.
   */
  heroImage?: (number | null) | Media;
  /**
   * Extra images further down the project detail page, each with an optional caption.
   */
  gallery?:
    | {
        image: number | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  type: 'image' | 'model' | 'figma' | 'nodegraph' | 'dice' | 'crate' | 'smartphone' | 'monitor';
  /**
   * Shown as the card artwork for this project.
   */
  image?: (number | null) | Media;
  /**
   * The .glb/.gltf file rendered in 3D for this project.
   */
  model?: (number | null) | Model;
  /**
   * Shown on the phone/monitor screen (its homescreen, or a site screenshot).
   */
  homeScreenImage?: (number | null) | Media;
  /**
   * Gradient/accent color: used as a placeholder while no image is set, as the mat/background behind an image card (Type = Image), and as a subtle tint elsewhere.
   */
  accentColorA?: string | null;
  accentColorB?: string | null;
  /**
   * Lower numbers appear first in the list.
   */
  order?: number | null;
  /**
   * Skills used on this project, powering the future skills-hover section.
   */
  skills?: (number | Skill)[] | null;
  /**
   * Other projects to cross-link on this project's page, e.g. a case study and the model/framework it applies. Add the link on both sides to cross-link them.
   */
  relatedProjects?: (number | Project)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Skills that can be linked to projects, powering a future skills-hover section.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "skills".
 */
export interface Skill {
  id: number;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  /**
   * Short description of this skill.
   */
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'models';
        value: number | Model;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'skills';
        value: number | Skill;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "models_select".
 */
export interface ModelsSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  category?: T;
  description?: T;
  links?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  content?: T;
  heroImage?: T;
  gallery?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  type?: T;
  image?: T;
  model?: T;
  homeScreenImage?: T;
  accentColorA?: T;
  accentColorB?: T;
  order?: T;
  skills?: T;
  relatedProjects?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "skills_select".
 */
export interface SkillsSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Content for the /about page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page".
 */
export interface AboutPage {
  id: number;
  /**
   * Portrait photo shown on the About page.
   */
  photo?: (number | null) | Media;
  /**
   * Small label shown above the title, e.g. "ABOUT · 2026"
   */
  category?: string | null;
  title: string;
  /**
   * Short intro shown under the title.
   */
  description: string;
  /**
   * Optional longer write-up, shown below the intro. Blank lines start a new paragraph; lines starting with "- " become a bullet list.
   */
  content?: string | null;
  /**
   * Schools/programmes, shown as a list on the About page. Drag to reorder.
   */
  education?:
    | {
        /**
         * School logo, shown next to the institution name.
         */
        logo?: (number | null) | Media;
        /**
         * School name, e.g. "NHL Stenden Leeuwarden"
         */
        institution: string;
        /**
         * Programme/degree, e.g. "Communication & Multimedia Design"
         */
        title: string;
        /**
         * e.g. "2024 - present"
         */
        period?: string | null;
        /**
         * Current / ongoing — highlights this entry's dot on the About page.
         */
        current?: boolean | null;
        /**
         * Skills linked to this programme, shown as chips beneath it.
         */
        skills?: (number | Skill)[] | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Jobs/roles, shown as a list on the About page. Drag to reorder.
   */
  experience?:
    | {
        /**
         * Company logo, shown next to the company name.
         */
        logo?: (number | null) | Media;
        /**
         * Company name, e.g. "EL-Websolutions"
         */
        company: string;
        /**
         * Job title, e.g. "Freelance Web Developer"
         */
        role: string;
        /**
         * e.g. "Feb 2024 - present"
         */
        period?: string | null;
        /**
         * Optional short line about the role.
         */
        description?: string | null;
        /**
         * Current / ongoing — highlights this entry's dot on the About page.
         */
        current?: boolean | null;
        /**
         * Skills used in this role, shown as chips beneath it.
         */
        skills?: (number | Skill)[] | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Content for the /contact page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page".
 */
export interface ContactPage {
  id: number;
  /**
   * Portrait photo shown on the Contact page.
   */
  photo?: (number | null) | Media;
  /**
   * Small label shown above the title, e.g. "CONTACT · 2026"
   */
  category?: string | null;
  title: string;
  /**
   * Short intro shown under the title.
   */
  description: string;
  /**
   * Shown as a mailto: link.
   */
  email: string;
  /**
   * Social links shown on the contact page, e.g. LinkedIn, GitHub, Instagram. Drag to reorder.
   */
  socials?:
    | {
        /**
         * Platform name, e.g. "LinkedIn"
         */
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Header content for the /projects page. The project list itself comes from the Projects collection, filterable by the Skills collection.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "skills-page".
 */
export interface SkillsPage {
  id: number;
  /**
   * Small label shown above the title, e.g. "PROJECTS · 2026"
   */
  category?: string | null;
  title: string;
  /**
   * Short intro shown under the title.
   */
  description: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page_select".
 */
export interface AboutPageSelect<T extends boolean = true> {
  photo?: T;
  category?: T;
  title?: T;
  description?: T;
  content?: T;
  education?:
    | T
    | {
        logo?: T;
        institution?: T;
        title?: T;
        period?: T;
        current?: T;
        skills?: T;
        id?: T;
      };
  experience?:
    | T
    | {
        logo?: T;
        company?: T;
        role?: T;
        period?: T;
        description?: T;
        current?: T;
        skills?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page_select".
 */
export interface ContactPageSelect<T extends boolean = true> {
  photo?: T;
  category?: T;
  title?: T;
  description?: T;
  email?: T;
  socials?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "skills-page_select".
 */
export interface SkillsPageSelect<T extends boolean = true> {
  category?: T;
  title?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}